Constant variables to upper case & snake case
BeelanMX/scrapCFEBot pull request #71
Opened 2021-10-04 23:34 UTC by AnaLucyGDL

Change the constant variables to the requested format

2021-10-05 21:22 UTC, tris460 requested changes

2021-10-05 21:46 UTC, wolftrax5 requested changes
No because we use the keyword "const" means need to be in UPERCASE, pls change it only where is need it.

2021-10-05 21:46 UTC, wolftrax5 commented on scrapperFunctions/index.js
> +function SCRAP_PAGE(BROWSER) {
The function not need to be in upercase, is not a constant, the name of this one not need change

2021-10-05 21:46 UTC, wolftrax5 commented on scrapperFunctions/index.js
> +  this.page = BROWSER.page;
Same here BROWSER should be on lowercase

2021-10-05 21:46 UTC, wolftrax5 commented on webScraping/cfeScrapper.js
> +const WAITING_TIME = 2000;
THIS IS THE CORRECT USE OF UPERCASE TO CONSTS

2021-10-05 21:46 UTC, wolftrax5 commented on webScraping/cfeScrapper.js
> +const ROW_SELECTOR = '#totProc';
Here too this is the correct use of const with upercase

2021-10-05 21:46 UTC, wolftrax5 commented on webScraping/cfeScrapper.js
> +  return BROWSER;
Bad use of uperCase

2021-11-24 18:43 UTC, wolftrax5 approved these changes

2021-11-24 18:43 UTC, wolftrax5 commented on utils/validator.js
> +  const validationfile = isFileHasLessHoursUpdate(hours);
for validationfile is correct use the camel case validationFile, but Is ok

2021-11-24 22:03 UTC, tris460 approved these changes

2021-11-26 15:46 UTC, merged