Add "Clean" command
BeelanMX/scrapCFEBot pull request #73
Opened 2021-11-24 00:09 UTC by AnaLucyGDL

2021-11-29 18:54 UTC, tris460 commented on commands/cfe.js
> +<<<<<<< HEAD
Delete it

2021-11-29 18:54 UTC, tris460 commented on commands/cfe.js
> +>>>>>>> bce62c39820daaabf8d738a20d7c9949cd59ff51
Delete it

2021-11-29 18:55 UTC, tris460 commented on commands/clean.js
> +    const fs = require('fs').promises
Add ';'

2021-11-29 18:57 UTC, tris460 commented on commands/clean.js
> +        console.log('Path')
Do you need this ?

2021-11-29 19:01 UTC, tris460 commented on commands/clean.js
> +      }).catch(err => {
I think, ESLint/Prettier uses parenthesis in the parameters 
(err)=>{...}

2021-11-29 19:05 UTC, tris460 commented on scrapperFunctions/index.js
> +<<<<<<< HEAD
Delete it

2021-11-29 19:06 UTC, tris460 commented on scrapperFunctions/index.js
> +>>>>>>> bce62c39820daaabf8d738a20d7c9949cd59ff51
Delete it

2021-11-29 19:07 UTC, tris460 commented on webScraping/cfeScrapper.js
> +// const ROUTE = './assets/Data-From-Table.json';
I have deleted this line a lot of times, but you always put it again, delete it please

2021-11-29 19:09 UTC, tris460 commented on webScraping/cfeScrapper.js
> +<<<<<<< HEAD
Delete it

2021-11-29 19:10 UTC, tris460 commented on commands/cfe.js
> +const VALIDATION = require('../utils/validator');
This changes are from the other PR

2021-11-29 19:12 UTC, tris460 requested changes
You have a lot of commentaries from the conflicts jaja

2021-11-29 23:04 UTC, tris460 commented on scrapperFunctions/index.js
> +const TABLE_TO_ARRAYS = (selector) => {
You mustn't have this

2021-11-29 23:05 UTC, tris460 commented on scrapperFunctions/index.js
> +const GET_ROWS = (selector) => {
Delete this function

2021-11-30 02:02 UTC, AnaLucyGDL commented on commands/clean.js
> +        console.log('Path')
No, was for a test.

2021-12-13 18:28 UTC, wolftrax5 approved these changes

2021-12-13 19:46 UTC, merged